### ISSUE TITLE
Use for authentication

### ISSUE THREAD

**Issue by sjashwin** [ageron/visual_crypto#1]
After creating the secret images, how do you merge the ciphered image and random secret to generate the original image?
 I want to authenticate a user when he provides the ciphered message.

**Comment by ageron** [comment]
You just overlay them: try printing the shared secret image on a transparent sheet of paper, then print the cyphered message on regular paper (using the exact same scale), then place the shared secret paper on top of the cyphered message, and ta-da!
Note that this procedure does not exactly recover the original message, as it performs (cyphered_message OR shared_secret) rather than (cyphered_message XOR shared_secret), so you get the original message plus random noise added on top.  It generally does not hurt, though.  Long story short, if you want to recover the original image programmatically, you need to compute (cyphered_message XOR  shared_secret).
